services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    ports:
      - 13378:80
    volumes:
      - /mnt/data/Media/Books/Audiobooks:/audiobooks
      # - /mnt/data/Media/Podcasts:/podcasts
      - /mnt/docker/audiobookshelf:/config
      - /mnt/docker/audiobookshelf/metadata:/metadata
    environment:
      - TZ=Australia/Perth
