version: "3.3"
services:
  stirling-pdf:
    image: docker.stirlingpdf.com/stirlingtools/stirling-pdf:latest
    ports:
      - "8083:8080"
    volumes:
      - /mnt/docker/StirlingPDF/trainingData:/usr/share/tessdata # Required for extra OCR languages
      - /mnt/docker/StirlingPDF/extraConfigs:/configs
      - /mnt/docker/StirlingPDF/customFiles:/customFiles/
      - /mnt/docker/StirlingPDF/logs:/logs/
      - /mnt/docker/StirlingPDF/pipeline:/pipeline/
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - LANGS=en_GB
