version: "3.8"

services:
  openobserve:
    # Using the SIMD image for AVX512/NEON performance benefits, as you requested.
    image: public.ecr.aws/zinclabs/openobserve:latest-simd
    container_name: openobserve
    restart: unless-stopped
    ports:
      # Exposes the OpenObserve UI and API on port 5080
      - "5080:5080"
    volumes:
      # Persists OpenObserve data in a Docker-managed volume
      - /mnt/docker/openobserve/data:/data
    environment:
      # Tells OpenObserve where to store data inside the container
      - ZO_DATA_DIR=/data
      # Root user credentials (only needed on the first run).
      # These are read from the .env file for better security.
      - ZO_ROOT_USER_EMAIL=${ZO_ROOT_USER_EMAIL}
      - ZO_ROOT_USER_PASSWORD=${ZO_ROOT_USER_PASSWORD}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5080/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
