---
# Before running this playbook, run the Proxmox post-install script:
# bash -c "$(curl -fsSL https://raw.githubusercontent.com/community-scripts/ProxmoxVE/main/tools/pve/post-pve-install.sh)"
# More info: https://community-scripts.github.io/ProxmoxVE/scripts?id=post-pve-install
#
# High availability is left on for now.
# Also create an SSH key on the controller:
# ssh-keygen -t rsa -b 4096

- name: Secure SSH, setup user abl030, and test
  hosts: proxmox_hosts
  remote_user: root
  gather_facts: false
  become: true # run tasks with root privileges
  vars:
    new_user: abl030

    # PUBLIC key of 'abl030' user ON YOUR ANSIBLE CONTROL NODE (NixOS)
    # This key will be added to the Proxmox host for the new_user.
    ssh_public_key_file_control_node: "~/.ssh/id_rsa.pub" # Or id_rsa.pub

    # PRIVATE key of 'abl030' user ON YOUR ANSIBLE CONTROL NODE (NixOS)
    # Needed for final verification task to connect as abl030.
    ssh_private_key_file_for_abl030_on_control_node: "~/.ssh/id_rsa" # Or id_rsa

  tasks:
    - name: Update apt cache and ensure sudo is installed
      ansible.builtin.apt:
        name: sudo
        state: present
        update_cache: true # Runs 'apt update' before install

    - name: Ensure the new user '{{ new_user }}' exists
      ansible.builtin.user:
        name: "{{ new_user }}"
        state: present
        shell: /bin/bash
        groups: sudo
        create_home: true

    - name: Set up authorized_keys for '{{ new_user }}'
      ansible.posix.authorized_key:
        user: "{{ new_user }}"
        state: present
        key: "{{ lookup('file', ssh_public_key_file_control_node) }}"

    - name: Allow '{{ new_user }}' to sudo without a password
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        state: present
        regexp: "^{{ new_user }} ALL="
        line: "{{ new_user }} ALL=(ALL) NOPASSWD: ALL"
        validate: /usr/sbin/visudo -cf %s

    - name: Disable SSH PasswordAuthentication
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?PasswordAuthentication"
        line: "PasswordAuthentication no"
        state: present
      notify: Restart sshd

    - name: Ensure SSH PubkeyAuthentication is enabled
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?PubkeyAuthentication"
        line: "PubkeyAuthentication yes"
        state: present
      notify: Restart sshd

    - name: Disable root login entirely via SSH
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?PermitRootLogin"
        line: "PermitRootLogin no" # Changed from prohibit-password
        state: present
      notify: Restart sshd

  handlers:
    - name: Restart sshd
      ansible.builtin.service:
        name: sshd # Or 'ssh' if that's the service name on Proxmox
        state: restarted
