---
- name: Configure Proxmox Dual NIC Networking (Management & WAN/LAN)
  hosts: proxmox_hosts # Or the specific host group from your inventory
  become: true
  gather_facts: false # We define facts manually to be explicit or rely on inventory

  vars:
    # --- Define your NICs and Network Configuration ---

    # WAN/LAN Network (for Host Internet and VMs) using the Realtek NIC
    wan_lan_nic_phys: "enp8s0"
    wan_lan_bridge_name: "vmbr0"
    wan_lan_bridge_ip_cidr: "192.168.1.12/24"

    # Management Network (for SSH, WebUI) using the USB NIC on a separate VLAN
    management_nic_phys: "enx00e04c78687d"
    management_bridge_name: "vmbr1"
    management_bridge_ip_cidr: "192.168.11.12/24"
    management_gateway_ip: "192.168.11.1" # <<< THIS LINE WAS MISSING

    # General Network Settings
    gateway_ip: "192.168.1.1" # The default gateway for the PRIMARY WAN/LAN
    dns_servers:
      - "192.168.1.1"
      - "8.8.8.8"

  pre_tasks:
    - name: Gather minimal facts if not already done by inventory
      ansible.builtin.setup:
        filter:
          - ansible_distribution
          - ansible_distribution_version
      when: ansible_distribution is not defined

    - name: Ensure ifupdown2 is installed for safe network reloading
      ansible.builtin.apt:
        name: ifupdown2
        state: present
        update_cache: yes

  tasks:
    - name: Backup the current /etc/network/interfaces file
      ansible.builtin.copy:
        src: /etc/network/interfaces
        dest: "/etc/network/interfaces.bak-{{ lookup('pipe', 'date +%Y%m%dT%H%M%S') }}"
        remote_src: true
        owner: root
        group: root
        mode: "0644"
      register: backup_result
      changed_when: false

    - name: Generate the new network configuration from template
      ansible.builtin.template:
        src: templates/interfaces.j2
        dest: /etc/network/interfaces
        owner: root
        group: root
        mode: "0644"
        backup: yes
      notify: Apply Network Changes

  handlers:
    - name: Apply Network Changes
      listen: "Apply Network Changes"
      ansible.builtin.command:
        cmd: "ifreload -a"
      register: network_apply
      changed_when: true
      failed_when: network_apply.rc != 0
