---
- name: Configure Proxmox Host for GPU Passthrough (with Auto-Reboot)
  hosts: proxmox_hosts
  become: true
  gather_facts: false

  tasks:
    - name: Ensure IOMMU is enabled in BIOS/UEFI (Manual Check Reminder)
      ansible.builtin.debug:
        msg: |
          IMPORTANT MANUAL CHECK: Ensure IOMMU (AMD-Vi) is ENABLED
          in your Proxmox host's BIOS/UEFI. Ansible cannot do this.

    - name: Set correct IOMMU kernel parameters in GRUB
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        regexp: "^GRUB_CMDLINE_LINUX_DEFAULT="
        line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet amd_iommu=on iommu=pt"'
        state: present
      notify:
        - Run update-grub
        - A reboot is required

    - name: Ensure core VFIO modules are loaded at boot
      ansible.builtin.blockinfile:
        path: /etc/modules
        block: |
          # Modules required for PCI passthrough
          vfio
          vfio_iommu_type1
          vfio_pci
        marker: "# ANSIBLE MANAGED BLOCK FOR VFIO MODULES"
        create: true
      notify:
        - Run update-initramfs
        - A reboot is required

    - name: Configure vfio-pci to claim the GPU at boot
      ansible.builtin.copy:
        dest: /etc/modprobe.d/vfio.conf
        content: "options vfio-pci ids=8086:56a6,8086:4f92 disable_vga=1"
        owner: root
        group: root
        mode: "0644"
      notify:
        - Run update-initramfs
        - A reboot is required

    - name: Blacklist native Intel GPU drivers to prevent race conditions
      ansible.builtin.copy:
        dest: /etc/modprobe.d/blacklist-intel-gpu.conf
        content: |
          blacklist i915
          blacklist xe
        owner: root
        group: root
        mode: "0644"
      notify:
        - Run update-initramfs
        - A reboot is required

    # This task ensures all pending handlers (like update-grub) are run before the reboot check.
    - name: Flush handlers to apply configurations
      ansible.builtin.meta: flush_handlers

    # This block handles the actual reboot. It will only run if the 'reboot_is_required'
    # fact was set by one of the handlers.
    - name: Reboot the server if configuration changes were made
      when: reboot_is_required | default(false)
      block:
        - name: Inform user about the required reboot
          ansible.builtin.debug:
            msg: "Configuration changed, rebooting the host in 30 seconds..."

        - name: Reboot host and wait for it to return
          ansible.builtin.reboot:
            reboot_timeout: 600 # 10 minutes
            pre_reboot_delay: 30 # Give us time to read the message

  # These handlers are the tasks that get notified by the main tasks above.
  handlers:
    - name: Run update-grub
      ansible.builtin.command: update-grub
      listen: "Run update-grub"

    - name: Run update-initramfs
      ansible.builtin.command: update-initramfs -u -k all
      listen: "Run update-initramfs"

    - name: Set reboot flag
      ansible.builtin.set_fact:
        reboot_is_required: true
      listen: "A reboot is required"
