---
keys:
  - &users
    - &ta age1k8che8dpr80th3x8wzv0nmfz8d8lc3vr22mpms4vvmmf7m89lenqazd7wg
  - &hosts
    - &asus age1tm5juz8dctz5asmdwzznq9ytwsw5hz5g7zvl9gud595jdkk0l5aql6vjxj

creation_rules:
  # path should be relative to the location of this file (.sops.yaml)
  - path_regex: secrets.yaml$
    key_groups:
      - age:
          - *ta
          - *asus
